#!/bin/sh
cd "$(dirname "$0")"
rm -rf lib/
rm -rf index.d.ts
mkdir lib
yarn
gulp stylesProduction
tsc ./src/ts/components/ui/form.tsx -d --jsx react --target ES5 --outDir ./lib
cp ./lib/form.d.ts ./
mv form.d.ts index.d.ts